import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { getUserFromId, User } from "@/lib/auth";
import { UserProvider } from "@/context/userContext";
import { SidePanel } from "@/components/sidePanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userId = cookieStore.get("userId")?.value;
  let user: User | null = null;

  if (userId) {
    user = await getUserFromId(userId);
  }

  return (
    <html lang="en">
      <body className={`antialiased bg-[url('/bg.png')] bg-cover`}>
        <UserProvider user={user}>
          <SidePanel />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
